# -*- coding: utf-8 -*-
"""student_analytics.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_bgg79ke1rFcbHmj38unFuE0K2kTHekg
"""

from collections import defaultdict


students = []


def create_student(name: str, roll: str, **marks) -> dict:
    """
    Create a student record.

    Args:
        name (str): Student name
        roll (str): Roll number
        **marks: Subject marks (math=90, python=80, etc.)

    Returns:
        dict: Student dictionary
    """

    if not name or not roll:
        raise ValueError("Name and roll are required")

    student = {
        "name": name,
        "roll": roll,
        "marks": marks,
        "attendance": 0.0
    }

    return student


def calculate_gpa(*marks: float, scale: float = 10.0) -> float:
    """
    Calculate GPA from marks.

    Args:
        *marks (float): Any number of marks
        scale (float): GPA scale (default 10)

    Returns:
        float: GPA value
    """

    if not marks:
        return 0.0

    avg = sum(marks) / len(marks)
    gpa = (avg / 100) * scale

    return round(gpa, 2)


def get_top_performers(students: list[dict], n: int = 5, subject: str = None) -> list[dict]:
    """
    Return top N performing students.

    Args:
        students (list): List of student dictionaries
        n (int): Number of students to return
        subject (str): Optional subject for ranking

    Returns:
        list: Top students
    """

    if not students:
        return []

    if subject:
        sorted_students = sorted(
            students,
            key=lambda s: s.get("marks", {}).get(subject, 0),
            reverse=True
        )
    else:
        sorted_students = sorted(
            students,
            key=lambda s: sum(s.get("marks", {}).values()) / max(len(s.get("marks", {})), 1),
            reverse=True
        )

    return sorted_students[:n]


def generate_report(student: dict, **options) -> str:
    """
    Generate formatted student report.

    Args:
        student (dict): Student record
        **options: include_rank, include_grade, verbose

    Returns:
        str: Report string
    """

    include_rank = options.get("include_rank", True)
    include_grade = options.get("include_grade", True)
    verbose = options.get("verbose", False)

    marks = student.get("marks", {})
    avg = sum(marks.values()) / max(len(marks), 1)

    report = f"Student: {student.get('name')} ({student.get('roll')})\n"
    report += f"Average: {round(avg,2)}\n"

    if verbose:
        report += f"Marks: {marks}\n"

    if include_grade:
        if avg >= 90:
            grade = "A"
        elif avg >= 75:
            grade = "B"
        elif avg >= 60:
            grade = "C"
        else:
            grade = "D"

        report += f"Grade: {grade}\n"

    if include_rank:
        report += "Rank: N/A\n"

    return report


def classify_students(students: list[dict]) -> dict:
    """
    Classify students into grade categories.

    Args:
        students (list): Student list

    Returns:
        dict: {'A':[], 'B':[], 'C':[], 'D':[]}
    """

    categories = defaultdict(list)

    if not students:
        return categories

    for student in students:

        marks = student.get("marks", {})
        avg = sum(marks.values()) / max(len(marks), 1)

        if avg >= 90:
            categories["A"].append(student)

        elif avg >= 75:
            categories["B"].append(student)

        elif avg >= 60:
            categories["C"].append(student)

        else:
            categories["D"].append(student)

    return dict(categories)



