# -*- coding: utf-8 -*-
"""Day-10|PartA_AM_Submission.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14WbMEM1w0r-8GbTtDm85w_JDS9vrlruR

1. Data Structure: Catalog
2. Add at least 15 products across 4 categories (electronics, clothing, books, food).
"""

from collections import defaultdict

catalog = {
    "SKU001": {"name": "Laptop", "price": 65000, "category": "electronics", "stock": 15, "rating": 4.5, "tags": ["computer", "work"]},
    "SKU002": {"name": "Smartphone", "price": 30000, "category": "electronics", "stock": 20, "rating": 4.3, "tags": ["mobile", "gadget"]},
    "SKU003": {"name": "Headphones", "price": 2500, "category": "electronics", "stock": 0, "rating": 4.1, "tags": ["music", "audio"]},
    "SKU004": {"name": "Smartwatch", "price": 12000, "category": "electronics", "stock": 8, "rating": 4.0, "tags": ["wearable", "fitness"]},

    "SKU005": {"name": "T-Shirt", "price": 800, "category": "clothing", "stock": 30, "rating": 3.9, "tags": ["casual", "cotton"]},
    "SKU006": {"name": "Jeans", "price": 2000, "category": "clothing", "stock": 10, "rating": 4.2, "tags": ["denim", "casual"]},
    "SKU007": {"name": "Jacket", "price": 3500, "category": "clothing", "stock": 0, "rating": 4.4, "tags": ["winter", "fashion"]},
    "SKU008": {"name": "Sneakers", "price": 4500, "category": "clothing", "stock": 12, "rating": 4.1, "tags": ["shoes", "sports"]},

    "SKU009": {"name": "Python Programming", "price": 600, "category": "books", "stock": 25, "rating": 4.7, "tags": ["programming", "education"]},
    "SKU010": {"name": "Data Science Handbook", "price": 900, "category": "books", "stock": 18, "rating": 4.6, "tags": ["data", "education"]},
    "SKU011": {"name": "AI Basics", "price": 750, "category": "books", "stock": 0, "rating": 4.2, "tags": ["ai", "technology"]},

    "SKU012": {"name": "Chocolate", "price": 150, "category": "food", "stock": 50, "rating": 4.5, "tags": ["sweet", "snack"]},
    "SKU013": {"name": "Coffee Beans", "price": 500, "category": "food", "stock": 40, "rating": 4.6, "tags": ["drink", "energy"]},
    "SKU014": {"name": "Olive Oil", "price": 1200, "category": "food", "stock": 14, "rating": 4.4, "tags": ["cooking", "healthy"]},
    "SKU015": {"name": "Green Tea", "price": 400, "category": "food", "stock": 22, "rating": 4.3, "tags": ["drink", "healthy"]},
}

"""Implement these functions using dict operations:

    A. search_by_tag(tag) → returns all products containing that tag (use defaultdict to group by tag)

    B. out_of_stock() → returns products with stock == 0 (dict comprehension with filter)

    C. price_range(min_price, max_price) → filter products by price range

    D. category_summary() → for each category: count, avg price, avg rating (use defaultdict(list))

    E. apply_discount(category, percent) → reduce prices for a category (dict comprehension)

    F. merge_catalogs(catalog1, catalog2) → merge two catalogs, handling duplicate SKUs (use | or **)
"""

# A. search_by_tag(tag) → returns all products containing that tag (use defaultdict to group by tag)

# def search_by_tag(tag):
#     result = []

#     for product in catalog.values():
#         if tag in product.get("tags"):
#             result.append(product.get("name"))

#     return result

def search_by_tag(tag):
    tag_map = defaultdict(list)

    for product in catalog.values():
        if tag in product.get("tags"):
            tag_map[tag].append(product.get("name"))

    return tag_map[tag]

print(search_by_tag("casual"))

# out_of_stock() → returns products with stock == 0 (dict comprehension with filter)

# def out_of_stock():
#   result= []
#   for sku, product in catalog.items():
#         if product.get("stock") == 0:
#             result.append(product.get("name"))

#   return result


def out_of_stock():
  result={}
  for sku, product in catalog.items():
        if product.get("stock") == 0:
            result[sku]=product.get("name")

  return result

print(out_of_stock())

# price_range(min_price, max_price) → filter products by price range
def price_range(min_price, max_price):
    price_result = {}

    for sku, product in catalog.items():
        price = product.get("price")
        if min_price <= price <= max_price:
            price_result[sku] = product.get("name")

    return price_result

price_range(500, 5000)

# category_summary() → for each category: count, avg price, avg rating (use defaultdict(list))
from collections import defaultdict

def category_summary():
    category_data = defaultdict(list)

    for product in catalog.values():
        category = product.get("category")
        category_data[category].append(product)

    result = {}

    for category, products in category_data.items():
        count = len(products)
        avg_price = sum(p.get("price", 0) for p in products) / count
        avg_rating = sum(p.get("rating", 0) for p in products) / count

        result[category] = {
            "count": count,
            "avg_price": avg_price,
            "avg_rating": avg_rating
        }

    return result

category_summary()

# apply_discount(category, percent) → reduce prices for a category (dict comprehension)
def apply_discount(category, percent):
    return {
        sku: {**product, "price": product.get("price", 0) * (1 - percent / 100)}
        if product.get("category") == category
        else product
        for sku, product in catalog.items()
    }
apply_discount("electronics", 10)

# merge_catalogs(catalog1, catalog2) → merge two catalogs, handling duplicate SKUs (use | or **)
def merge_catalogs(catalog1, catalog2):
    return catalog1 | catalog2

catalog1 = {"SKU001": {"name": "Laptop"}}
catalog2 = {"SKU002": {"name": "Phone"}}

merge_catalogs(catalog1, catalog2)

